# Generated by Django 3.0.6 on 2020-05-08 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20200508_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='friends_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='requests',
        ),
        migrations.AddField(
            model_name='customuser',
            name='requests',
            field=models.ManyToManyField(related_name='requests_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
