# Generated by Django 3.0.6 on 2020-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_remove_message_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_my',
            field=models.BooleanField(default=True),
        ),
    ]
