# Generated by Django 3.0.6 on 2020-05-09 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_message_is_my'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_my',
        ),
        migrations.AddField(
            model_name='message',
            name='from_who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whom_msg', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='to_who',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_msg', to=settings.AUTH_USER_MODEL),
        ),
    ]
